### ISSUE TITLE
No such module 'MachO.dyld_images' when compiling

### ISSUE THREAD

**Issue by sourcelocation** [Odyssey-Team/Odyssey#51]
When I try to compile Odyssey with Xcode it gives me this error `No such module 'MachO.dyld_images'` in `ViewController.swift` . How can I fix this? Thanks

**Comment by demhademha** [comment]
Make sure that you clone with the **--recursive** option

**Comment by ExeRhythm** [comment]
ok, thanks

**Comment by ExeRhythm** [comment]
Someone :(

**Comment by ExeRhythm** [comment]
:(

**Comment by ExeRhythm** [comment]
Thanks, I’ll try this in a few days.
