### ISSUE TITLE
how can i call jailbreakd to fixupdylib?

### ISSUE THREAD

**Issue by youngzzzzzzz** [Odyssey-Team/Odyssey#70]
i want to dlopen dylib in /var
there is a way to do so like this:
https://github.com/jakeajames/rootlessJB3/blob/69a0d9e768289c7ae94aa45d8aaa87f153f25089/rootlessJB/payloads_source/amfid_payload/common.m#L81

how can i do similar things with odyssey?

**Comment by youngzzzzzzz** [comment]
done by myself

**Comment by demhademha** [comment]
Were you able to solve this: what was the solution?
